# @host=localhost:8000
@host = 


### test
GET https://{{host}}/

### init
POST http://{{host}}/init
Content-Type: application/json
{
    "Player": {
        "id": "1",
        "Cards": ["CuSO4·5H2O", "H2SO4", "HCl", "CaCO3", "Cu(OH)2", "NH4Cl", "H3PO4", "NaOH"],
    }
}

###PlaceCard
POST http://{{host}}/place-card
Content-Type: application/json
{
    "Card": {
        "Beaker": "2",
        "CardName": "CuSO4·5H2O",
        "Player": "2",
        "Pos": "3"
    }
}

### Endturn
POST http://{{host}}/endturn
Content-Type: application/json
{
    "Turn": "1",
    "CurrentPlayer": "2"
}
