@host=localhost:8000
# @host=sc.jiangyq.com/api


### test
GET https://{{host}}/

### init
POST http://{{host}}/init_cards
Content-Type: application/json

{
    "Player": {
        "id": "1",
        "Cards": ["CuSO4·5H2O", "H2SO4", "HCl", "CaCO3", "Cu(OH)2", "NH4Cl", "H3PO4", "NaOH"],
    }
}

###PlaceCard
POST http://{{host}}/react
Content-Type: application/json

{
    "score": -1,
    "water": 6,
    "beaker": [
        
    ],
    "card": {"name": "HCl", "no": 1}
}

### Endturn
POST http://{{host}}/endturn
Content-Type: application/json
{
    "Turn": "1",
    "CurrentPlayer": "2"
}
